name: deploy-kind

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      helm-values-path:
        required: true
        type: string
      helm-release-name:
        required: true
        type: string

jobs:
  deploy-to-kind:
    runs-on: ubuntu-latest
    name: Deploy to Kind (${{ inputs.environment }})
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kind cluster
        run: kind create cluster --config cluster.yml --wait 120s

      - name: Install Helm chart (dry-run)
        run: |
          helm install todoapp ./helm-charts/todoapp \
            --namespace ${{ inputs.environment }} \
            --create-namespace \
            --values ${{ inputs.helm-values-path }} \
            --dry-run

      - name: Deploy with Helm (atomic)
        run: |
          helm upgrade --install todoapp ./helm-charts/todoapp \
            --namespace ${{ inputs.environment }} \
            --create-namespace \
            --values ${{ inputs.helm-values-path }} \
            --atomic
